In [67]:
from numpy import loadtxt
from tensorflow.keras.models import load_model

# load model
model = load_model('model.h5')
# summarize model.
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 50)                5050      
                                                                 
 dense_2 (Dense)             (None, 25)                1275      
                                                                 
 dense_3 (Dense)             (None, 3)                 78        
                                                                 
Total params: 6,903
Trainable params: 6,903
Non-trainable params: 0
_________________________________________________________________


In [68]:
import os
import pandas as pd
import numpy as np
with open('testResources/prediction_request.json') as json_file:
    data = pd.read_json(json_file)

data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             1            1             3            3

In [74]:
y_pred = model.predict(data)
species = {0:'Setosa',1:'Versicolor',2:'Virginica' }
y_pred

1/1 [==============================] - 0s 15ms/step


array([[8.1427773e-12, 5.0333355e-08, 1.0000000e+00]], dtype=float32)

In [77]:
species[np.argmax(y_pred)]

'Virginica'

In [70]:
y_pred[0][0]

array([8.1427773e-12, 5.0333355e-08, 1.0000000e+00], dtype=float32)

In [71]:
import iris_predictor

dp = iris_predictor.IrisPredictor()
status = dp.predict_single_record(data)
status


1/1 [==============================] - 0s 50ms/step
[8.1427773e-12 5.0333355e-08 1.0000000e+00]


array([8.1427773e-12, 5.0333355e-08, 1.0000000e+00], dtype=float32)

In [72]:
status[0]

8.142777e-12

In [73]:
bool(status[0]) is False


False

In [66]:
bool(False)

False