In [97]:
from numpy import loadtxt
from tensorflow.keras.models import load_model

# load model
model = load_model('model.h5')
# summarize model.
model.summary()

OSError: Unable to open file (file signature not found)

In [98]:
import os
import pandas as pd
import numpy as np
with open('testResources/prediction_request.json') as json_file:
    data = pd.read_json(json_file)

data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             1            1             3            3

In [94]:
y_pred = model.predict(data)
species = {0:'Setosa',1:'Versicolor',2:'Virginica' }
y_pred

1/1 [==============================] - 0s 42ms/step


array([[0.00204343, 0.00500577, 0.9929508 ]], dtype=float32)

In [99]:
species[np.argmax(y_pred)]

'Setosa'

In [100]:
data = pd.DataFrame({"Sepal.Length": [4.6],"Sepal.Width": [3.1],"Petal.Length": [1.5],"Petal.Width": [0.2]})

y_pred = model.predict(data)
species = {0:'Setosa',1:'Versicolor',2:'Virginica' }
print(y_pred)
species[np.argmax(y_pred)]

1/1 [==============================] - 0s 16ms/step
[[9.9654680e-01 3.4511969e-03 2.0419534e-06]]


'Setosa'

In [70]:
y_pred[0][0]

array([8.1427773e-12, 5.0333355e-08, 1.0000000e+00], dtype=float32)

In [71]:
import iris_predictor

dp = iris_predictor.IrisPredictor()
status = dp.predict_single_record(data)
status


1/1 [==============================] - 0s 50ms/step
[8.1427773e-12 5.0333355e-08 1.0000000e+00]


array([8.1427773e-12, 5.0333355e-08, 1.0000000e+00], dtype=float32)

In [112]:

from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import pickle

with open('model.h5', 'rb') as open_file:
    model = pickle.load(open_file)
data = pd.DataFrame({"Sepal.Length": [4.6],"Sepal.Width": [3.1],"Petal.Length": [1.5],"Petal.Width": [0.2]})
y_pred = model.predict(data)
print(y_pred)

y_pred[0]

['setosa']


C:\Users\brand\anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.1.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


'setosa'