##### Prediction model of type of iris plant via Tensorflow

In [1]:
# Imports
import seaborn as sns
import pandas as pd
import numpy as np

from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Activation
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model;

2022-10-24 12:14:17.587061: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-24 12:14:17.676668: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-24 12:14:17.680086: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-24 12:14:17.680096: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

##### Sources:
https://machinelearningmastery.com/save-load-keras-deep-learning-models/
https://wellsr.com/python/python-tensorflow-2-for-classification/

In [2]:
# load data
dataset = sns.load_dataset('iris')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# divide dependent and independent variable
X = dataset.drop(['species'], axis=1)
y = pd.get_dummies(dataset.species, prefix='output')
y

output_setosa  output_versicolor  output_virginica
0                1                  0                 0
1                1                  0                 0
2                1                  0                 0
3                1                  0                 0
4                1                  0                 0
..             ...                ...               ...
145              0                  0                 1
146              0                  0                 1
147              0                  0                 1
148              0                  0                 1
149              0                  0                 1

[150 rows x 3 columns]

In [4]:
X = X.values
y = y.values

In [5]:
# train - test split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=39)
X_test

array([[4.6, 3.4, 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.2],
       [6.2, 3.4, 5.4, 2.3],
       [5.8, 2.7, 3.9, 1.2],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [4.7, 3.2, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [5.7, 2.8, 4.5, 1.3],
       [5.1, 3.7, 1.5, 0.4],
       [6.9, 3.1, 5.4, 2.1],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [7.2, 3.2, 6. , 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5.8, 2.6, 4. , 1.2],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.6, 5.6, 1.4],
       [5.5, 2.6, 4.4, 1.2]])

In [6]:
# Removed for now! Don't uncomment

#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [7]:
# Create model
input_1 = Input(shape=(X_train.shape[1],))
l1 = Dense(100, activation='relu')(input_1)
l2 = Dense(50, activation='relu')(l1)
l3 = Dense(25, activation='relu')(l2)
output_1 = Dense(y_train.shape[1], activation='softmax')(l3)

model = Model(inputs = input_1, outputs = output_1)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

2022-10-24 12:14:18.734986: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-24 12:14:18.735636: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-24 12:14:18.735771: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-10-24 12:14:18.735886: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-10-24 12:14:18.735991: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [8]:
# Fit the model
history = model.fit(X_train, y_train, batch_size=4, epochs=20, verbose=1, validation_split=0.20)

Epoch 1/20
24/24 [==============================] - 1s 14ms/step - loss: 1.2133 - acc: 0.5625 - val_loss: 0.9790 - val_acc: 0.7500
Epoch 2/20
24/24 [==============================] - 0s 1ms/step - loss: 0.9292 - acc: 0.6562 - val_loss: 0.8477 - val_acc: 0.7500
Epoch 3/20
24/24 [==============================] - 0s 1ms/step - loss: 0.7659 - acc: 0.6771 - val_loss: 0.7302 - val_acc: 0.8333
Epoch 4/20
24/24 [==============================] - 0s 1ms/step - loss: 0.6142 - acc: 0.8333 - val_loss: 0.6346 - val_acc: 0.6250
Epoch 5/20
24/24 [==============================] - 0s 1ms/step - loss: 0.5147 - acc: 0.8333 - val_loss: 0.5510 - val_acc: 0.6667
Epoch 6/20
24/24 [==============================] - 0s 1ms/step - loss: 0.4456 - acc: 0.8750 - val_loss: 0.5160 - val_acc: 0.6667
Epoch 7/20
24/24 [==============================] - 0s 1ms/step - loss: 0.3890 - acc: 0.9375 - val_loss: 0.4811 - val_acc: 0.6667
Epoch 8/20
24/24 [==============================] - 0s 1ms/step - loss: 0.3452 - acc: 0.9

In [9]:
# Evaluate the model
score = model.evaluate(X_test, y_test, verbose=1)

print("Test Accuracy:", score[1])

1/1 [==============================] - 0s 82ms/step - loss: 0.0973 - acc: 0.9667
Test Accuracy: 0.9666666388511658


In [10]:
# Make predictions
model.predict(X_test).flatten()

1/1 [==============================] - 0s 42ms/step


array([9.96100545e-01, 3.89944669e-03, 2.73981660e-09, 9.93250251e-01,
       6.74974173e-03, 5.96481886e-09, 1.33020842e-06, 1.19032292e-02,
       9.88095462e-01, 5.10520022e-03, 9.67584014e-01, 2.73107719e-02,
       9.93791401e-01, 6.20865868e-03, 1.07821112e-08, 9.93804514e-01,
       6.19542645e-03, 4.03691081e-09, 9.33732565e-07, 9.26996209e-03,
       9.90729094e-01, 9.92412031e-01, 7.58789806e-03, 9.73922454e-09,
       3.92924562e-07, 7.19960080e-03, 9.92799997e-01, 3.04772448e-06,
       7.92910457e-02, 9.20705855e-01, 6.89177075e-04, 5.35943449e-01,
       4.63367432e-01, 9.97474730e-01, 2.52525532e-03, 5.10407216e-10,
       3.91955473e-06, 4.06962186e-02, 9.59299803e-01, 1.55505482e-02,
       9.64398324e-01, 2.00510658e-02, 1.31233782e-03, 9.24529731e-01,
       7.41579458e-02, 2.39793700e-03, 9.03488755e-01, 9.41133425e-02,
       1.63909283e-06, 2.87260469e-02, 9.71272230e-01, 4.02583993e-07,
       1.04523832e-02, 9.89547133e-01, 5.62060961e-07, 8.39887466e-03,
      

In [11]:
# Save the model in .h5 format
model.save("model.h5")
print("Saved model to disk")

Saved model to disk


In [12]:
# Load the model to test
model = load_model('model.h5')
# summarize model.
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 50)                5050      
                                                                 
 dense_2 (Dense)             (None, 25)                1275      
                                                                 
 dense_3 (Dense)             (None, 3)                 78        
                                                                 
Total params: 6,903
Trainable params: 6,903
Non-trainable params: 0
_________________________________________________________________


In [13]:
# Check data
data1 = pd.DataFrame({"Sepal.Length": [4.9],"Sepal.Width": [2.5],"Petal.Length": [4.5],"Petal.Width": [1.7]})
data2 = pd.DataFrame({"Sepal.Length": [4.6],"Sepal.Width": [3.1],"Petal.Length": [1.5],"Petal.Width": [0.2]})

y_pred1 = model.predict(data1)
y_pred2 = model.predict(data2)
species = {0:'Setosa',1:'Versicolor',2:'Virginica' }
print(y_pred1,y_pred2)
species[np.argmax(y_pred1)],species[np.argmax(y_pred2)]

1/1 [==============================] - 0s 12ms/step
[[1.6046788e-05 2.4116306e-02 9.7586763e-01]] [[9.9255204e-01 7.4479925e-03 1.1362550e-08]]


('Virginica', 'Setosa')